# Generated by Django 2.1.3 on 2019-09-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im1', models.CharField(max_length=255)),
                ('heading1', models.CharField(max_length=255)),
                ('info1', models.CharField(max_length=255)),
                ('im2', models.CharField(max_length=255)),
                ('heading2', models.CharField(max_length=255)),
                ('info2', models.CharField(max_length=255)),
                ('im3', models.CharField(max_length=255)),
                ('heading3', models.CharField(max_length=255)),
                ('info3', models.CharField(max_length=255)),
                ('im4', models.CharField(max_length=255)),
                ('heading4', models.CharField(max_length=255)),
                ('info4', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=255)),
                ('info1', models.CharField(max_length=255)),
                ('heading2', models.CharField(max_length=255)),
                ('info2', models.CharField(max_length=255)),
                ('heading3', models.CharField(max_length=255)),
                ('info3', models.CharField(max_length=255)),
                ('heading4', models.CharField(max_length=255)),
                ('info4', models.CharField(max_length=255)),
                ('heading5', models.CharField(max_length=255)),
                ('info5', models.CharField(max_length=255)),
                ('heading6', models.CharField(max_length=255)),
                ('info6', models.CharField(max_length=255)),
            ],
        ),
    ]
