# Generated by Django 2.1.3 on 2019-09-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imag',
            name='im1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imag',
            name='im2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imag',
            name='im3',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imag',
            name='im4',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
